version: '3.8'

# Docker Compose with LOCAL parsing (no cloud services)
# Privacy-first configuration for sensitive documents

services:
  ollama:
    image: ollama/ollama:latest
    container_name: rma-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  chromadb:
    image: chromadb/chroma:0.4.24  # Pin to 0.4.24 for compatibility with Python client
    container_name: rma-chromadb
    ports:
      - "8005:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped

  notes-service:
    build:
      context: ./services/notes-service
      dockerfile: Dockerfile
    container_name: rma-notes-service
    ports:
      - "8100:8100"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  doc-processor:
    build:
      context: ./services/doc-processor
      dockerfile: Dockerfile.local
    container_name: rma-doc-processor
    ports:
      - "8101:8101"
    environment:
      # Enable local parsing (no cloud)
      - USE_LOCAL_PARSING=true
      - OLLAMA_URL=http://ollama:11434
      - VISION_MODEL=llava:13b
      - TEXT_MODEL=llama3.2
      # Optional: LlamaParse fallback (leave empty for local-only)
      - LLAMA_PARSE_API_KEY=
    depends_on:
      - ollama
    restart: unless-stopped

  rag-service:
    build:
      context: ./services/rag-service
      dockerfile: Dockerfile
    container_name: rma-rag-service
    ports:
      - "8102:8102"
    volumes:
      - ./manuals:/manuals
    environment:
      - OLLAMA_URL=http://ollama:11434
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - MANUALS_PATH=/manuals
    depends_on:
      - ollama
      - chromadb
    restart: unless-stopped

  client-rag-service:
    build:
      context: ./services/client-rag-service
      dockerfile: Dockerfile
    container_name: rma-client-rag-service
    ports:
      - "8104:8104"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    depends_on:
      - ollama
      - chromadb
    restart: unless-stopped

  upload-service:
    build:
      context: ./services/upload-service
      dockerfile: Dockerfile
    container_name: rma-upload-service
    ports:
      - "8103:8103"
    volumes:
      - upload_data:/data/uploads
    environment:
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
      - UPLOAD_DIR=/data/uploads
      - DOC_PROCESSOR_URL=http://doc-processor:8101
      - CLIENT_RAG_URL=http://client-rag-service:8104
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:3000}
    depends_on:
      - doc-processor
      - client-rag-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rma-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_NOTES_SERVICE_URL=http://localhost:8100
      - NEXT_PUBLIC_DOC_PROCESSOR_URL=http://localhost:8101
      - NEXT_PUBLIC_RAG_SERVICE_URL=http://localhost:8102
      - NEXT_PUBLIC_UPLOAD_SERVICE_URL=http://localhost:8103
    depends_on:
      - notes-service
      - doc-processor
      - rag-service
      - upload-service
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:  # Shared ChromaDB storage for all collections (manuals + client docs)
  upload_data:

networks:
  default:
    name: rma-network

# PRIVACY NOTES:
# This configuration uses LOCAL document parsing only.
# No documents are sent to external cloud services.
# All processing happens on your infrastructure.
# GDPR compliant for sensitive financial documents.
