version: '3.8'

# Edge Coordinator Stack - FIXED VERSION
# Fixes:
# 1. Uses local build with heartbeat fix
# 2. Better networking configuration
# 3. Handles long model loading times

services:
  coordinator:
    image: ghcr.io/st7ma784/cmacatalyst/coordinator:latest
    container_name: edge-coordinator
    restart: unless-stopped
    # Use host network to avoid Docker IP issues
    network_mode: host
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DHT_PORT=8468
      - DHT_ENABLED=true
      - NODE_ENV=production
      # Increase worker timeout to handle model loading
      - WORKER_TIMEOUT_SECONDS=300  # 5 minutes
      - HEARTBEAT_TIMEOUT_SECONDS=90  # 1.5 minutes
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: edge-tunnel
    restart: always
    # Tunnel still needs bridge network to communicate with coordinator
    network_mode: host
    command: tunnel --url http://localhost:8080 --no-autoupdate
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 1.0.0.1
    extra_hosts:
      - "api.cloudflare.com:104.16.132.229"
      - "api.cloudflare.com:104.16.133.229"

  local-worker:
    # Build from local source with fixes
    build:
      context: ./worker-containers/universal-worker
      dockerfile: Dockerfile.optimized
    container_name: edge-local-worker
    restart: unless-stopped
    # Use host network so coordinator sees proper hostname
    network_mode: host
    environment:
      - WORKER_TYPE=auto
      - COORDINATOR_URL=http://localhost:8080
      - USE_TUNNEL=false
      - WORKER_ID=edge-local-worker
      # Keep heartbeat alive during model loading
      - HEARTBEAT_INTERVAL=45  # Send heartbeat every 45 seconds
      - MODEL_LOAD_TIMEOUT=600  # Allow 10 minutes for model loading
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    dns:
      - 1.1.1.1
      - 8.8.8.8

# Usage:
# docker-compose -f edge-coordinator-fixed.yml up -d --build
#
# Changes from original:
# 1. Uses host networking - no more 172.x.x.x IPs
# 2. Builds worker locally with heartbeat fix
# 3. Longer timeouts for model loading
# 4. More frequent heartbeats to keep worker alive
