version: '3.8'

# Edge Coordinator Stack
# Run this on any always-on machine to act as a distributed coordinator
# Zero configuration needed - just run and it auto-registers at api.rmatool.org.uk

services:
  coordinator:
    image: ghcr.io/st7ma784/cmacatalyst/coordinator:latest
    container_name: edge-coordinator
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8468:8468/udp"  # DHT port
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DHT_PORT=8468
      - DHT_ENABLED=true
      - NODE_ENV=production
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - edge-network

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: edge-tunnel
    restart: always  # Always restart on disconnect
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared-config.yml:/etc/cloudflared/config.yml:ro
      - ./tunnel-credentials.json:/etc/cloudflared/credentials.json:ro
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 1.0.0.1
    extra_hosts:
      - "api.cloudflare.com:104.16.132.229"
      - "api.cloudflare.com:104.16.133.229"
    networks:
      - edge-network
    # No depends_on - coordinator should run independently

  registrar:
    image: ghcr.io/st7ma784/cmacatalyst/universal-worker:latest
    container_name: edge-registrar
    restart: always  # Keep trying to register
    environment:
      - WORKER_TYPE=edge
      - COORDINATOR_URL=https://api.rmatool.org.uk
      - TUNNEL_URL=https://edge-1.rmatool.org.uk
      - LOCAL_COORDINATOR_URL=http://coordinator:8080
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 1.0.0.1
    networks:
      - edge-network
    # No depends_on - should keep trying independently

  local-worker:
    image: ghcr.io/st7ma784/cmacatalyst/universal-worker:latest
    container_name: edge-local-worker
    restart: unless-stopped
    environment:
      - WORKER_TYPE=auto  # Auto-detect GPU/CPU capabilities
      - COORDINATOR_URL=http://coordinator:8080  # Direct local connection
      - USE_TUNNEL=false  # No tunnel needed - local connection
      - WORKER_ID=edge-local-worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - edge-network
    depends_on:
      coordinator:
        condition: service_healthy

networks:
  edge-network:
    driver: bridge

# Usage:
# docker-compose -f edge-coordinator.yml up -d
#
# This will:
# 1. Start coordinator on port 8080
# 2. Start local worker (auto-detects GPU/CPU)
# 3. Create Cloudflare Tunnel to coordinator
# 4. Register tunnel at api.rmatool.org.uk
# 5. Accept worker registrations from anywhere
#
# The local worker keeps the coordinator active and provides
# immediate compute capacity without external network hops.
#
# To stop:
# docker-compose -f edge-coordinator.yml down
