apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-inbox
  namespace: mordecai
  labels:
    app: document-inbox
    service: document-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-inbox
  template:
    metadata:
      labels:
        app: document-inbox
    spec:
      containers:
      - name: document-inbox
        image: mordecai/document-inbox:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: S3_BUCKET
          value: "mordecai-documents"
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: document-inbox-service
  namespace: mordecai
spec:
  selector:
    app: document-inbox
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-processor
  namespace: mordecai
  labels:
    app: ocr-processor
    service: document-processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ocr-processor
  template:
    metadata:
      labels:
        app: ocr-processor
    spec:
      containers:
      - name: ocr-processor
        image: mordecai/ocr-processor:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: NODE_ENV
          value: "production"
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: S3_BUCKET
          value: "mordecai-documents"
        - name: USE_AWS_TEXTRACT
          value: "true"
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-processor-service
  namespace: mordecai
spec:
  selector:
    app: ocr-processor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ocr-processor-hpa
  namespace: mordecai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ocr-processor
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: document-processing-config
  namespace: mordecai
data:
  max-file-size: "10485760"  # 10MB
  supported-formats: "pdf,doc,docx,jpg,jpeg,png,gif,bmp"
  ocr-confidence-threshold: "0.8"
  auto-approve-threshold: "0.9"
