version: '3.8'

services:
  ollama-rag:
    build: .
    container_name: ollama-rag-demo
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ./documents:/documents
      - ./data/vectorstore:/data/vectorstore
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"  # Ollama API
      - "8000:8000"    # RAG application
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true

volumes:
  ollama_data:
