# Example GitHub Actions workflow for building the universal worker
# This workflow is optimized for GitHub Actions disk space limits

name: Build Universal Worker

on:
  push:
    branches: [ master, main ]
    paths:
      - 'RMA-Demo/worker-containers/universal-worker/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'RMA-Demo/worker-containers/universal-worker/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/universal-worker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check disk space before build
      run: |
        echo "Disk space before build:"
        df -h /
        echo "Docker disk usage:"
        docker system df

    - name: Free up disk space
      run: |
        # Remove unnecessary packages to free up space
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        echo "Disk space after cleanup:"
        df -h /

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:latest
          network=host

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./RMA-Demo/worker-containers/universal-worker
        file: ./RMA-Demo/worker-containers/universal-worker/Dockerfile.optimized
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Clean up Docker to free space
      if: always()
      run: |
        docker system prune -af --volumes
        echo "Disk space after Docker cleanup:"
        df -h /

    - name: Check final disk space
      if: always()
      run: |
        echo "Final disk space:"
        df -h /
        echo "Docker disk usage:"
        docker system df

    - name: Image size report
      if: success()
      run: |
        echo "Built image sizes:"
        docker images '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}' --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"
